<?php

declare(strict_types=1);

namespace Trunk\Pipeline\Console;

use Trunk\Contracts\Console\Command;
use Trunk\Contracts\Console\CommandDefinition;
use Trunk\Contracts\Console\CommandInput;
use Trunk\Contracts\Console\CommandOutput;
use Trunk\Contracts\Console\Exception\CommandFailedException;
use Trunk\Foundation\Runtime;
use Trunk\Support\FileWriter;

/**
 * `trunk make:pipeline ImportCustomers` writes app/Pipelines/ImportCustomers.php. The first time it
 * runs it also writes app/Jobs/RunPipelineChunk.php, a thin generated job that lets `trunk build`'s
 * existing app/Jobs discovery pick it up with no changes to the queue package — see docs/pipelines.md.
 * Neither file is ever overwritten.
 */
final readonly class MakePipelineCommand implements Command
{
    public function __construct(private Runtime $runtime, private FileWriter $files = new FileWriter()) {}

    public function definition(): CommandDefinition
    {
        return new CommandDefinition('make:pipeline', 'Create a pipeline', ['Name' => 'the pipeline class name in PascalCase, e.g. ImportCustomers'], requiredArguments: 1);
    }

    public function handle(CommandInput $input, CommandOutput $output): int
    {
        $name = (string) $input->argument(0);

        if (preg_match('/^[A-Z][A-Za-z0-9]{0,60}$/D', $name) !== 1) {
            throw new CommandFailedException('The pipeline name must be PascalCase letters and digits, e.g. ImportCustomers.');
        }

        $path = $this->runtime->basePath . '/app/Pipelines/' . $name . '.php';

        if (file_exists($path)) {
            throw new CommandFailedException('app/Pipelines/' . $name . '.php already exists; nothing was overwritten.');
        }

        $directory = $this->runtime->basePath . '/app/Pipelines';

        if (!is_dir($directory) && !mkdir($directory, 0o755, true) && !is_dir($directory)) {
            throw new CommandFailedException('app/Pipelines could not be created.');
        }

        $this->files->write($path, <<<PHP
            <?php

            declare(strict_types=1);

            namespace App\\Pipelines;

            use Trunk\\Pipeline\\Pipeline;
            use Trunk\\Pipeline\\PipelineBuilder;
            use Trunk\\Pipeline\\Sink\\ArraySink;
            use Trunk\\Pipeline\\Source\\ArraySource;

            /**
             * Replace ArraySource/ArraySink with a real source and sink (CsvSource, DatabaseSink, ApiSource,
             * ApiSink, or your own Source/Sink implementation), and inject whatever they need (a Connection,
             * an HTTP client) through this class's own constructor. Add stages with ->through(new SomeStage()),
             * one call per stage, between from() and into().
             */
            final readonly class {$name} implements Pipeline
            {
                public function define(PipelineBuilder \$pipeline): void
                {
                    \$pipeline->from(new ArraySource([]))
                        ->into(new ArraySink())
                        ->chunk(500);
                }
            }

            PHP);

        $this->ensureRunnerJob();

        $output->success('Created app/Pipelines/' . $name . '.php');
        $output->line('  Add it to config/pipeline.php\'s list, then run "trunk pipeline:run ' . $name . '".');

        return 0;
    }

    private function ensureRunnerJob(): void
    {
        $path = $this->runtime->basePath . '/app/Jobs/RunPipelineChunk.php';

        if (file_exists($path)) {
            return;
        }

        $directory = $this->runtime->basePath . '/app/Jobs';

        if (!is_dir($directory) && !mkdir($directory, 0o755, true) && !is_dir($directory)) {
            throw new CommandFailedException('app/Jobs could not be created.');
        }

        $this->files->write($path, <<<'PHP'
            <?php

            declare(strict_types=1);

            namespace App\Jobs;

            use Trunk\Pipeline\PipelineRunner;
            use Trunk\Queue\Job\Job;
            use Trunk\Queue\Job\JobOptions;

            /**
             * Generated by `trunk make:pipeline`, once. Every pipeline shares this one job: reading a chunk,
             * transforming it, writing it, advancing the run and dispatching the next chunk (or marking the
             * run complete) all happen in PipelineRunner. Do not edit by hand; a pipeline's own behaviour
             * belongs in its own class under app/Pipelines.
             */
            final readonly class RunPipelineChunk implements Job
            {
                /**
                 * @param class-string<\Trunk\Pipeline\Pipeline> $pipeline
                 */
                public function __construct(
                    public string $pipeline,
                    public int $runId,
                    public int $offset,
                    public int $limit,
                ) {}

                public function handle(PipelineRunner $runner): void
                {
                    $runner->runChunk($this->pipeline, $this->runId, $this->offset, $this->limit);
                }

                public static function options(): JobOptions
                {
                    return new JobOptions(tries: 3, backoff: [30, 120, 600], timeout: 300, queue: 'pipelines');
                }
            }

            PHP);
    }
}
