<?php

declare(strict_types=1);

namespace Trunk\Orm\Compiler;

use BackedEnum;
use Trunk\Orm\Exception\MappingException;
use Trunk\Orm\Mapping\ColumnMetadata;
use Trunk\Orm\Mapping\EntityMetadata;
use Trunk\Orm\Mapping\RelationMetadata;
use Trunk\Orm\Mapping\Type;
use Trunk\Support\ClassName;
use Trunk\Support\CodeNames;

/**
 * Emits build/orm.php. Everything written into a code position (class names, property names) is
 * validated again here, and every string value goes through var_export(), so no mapped name can
 * inject code into the generated file.
 */
final class OrmCodeGenerator
{
    private const string CONVERT = '\Trunk\Orm\Mapping\Convert';

    /**
     * @param array<class-string, EntityMetadata> $metadata
     */
    public function generate(array $metadata): string
    {
        $metaCode = [];
        $mapperCode = [];

        foreach ($metadata as $class => $entity) {
            $metaCode[] = '        ' . self::literal($class) . ' => ' . $this->metadata($entity) . ',';
            $mapperCode[] = '        ' . self::literal($class) . ' => ' . $this->mapper($entity) . ',';
        }

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by `trunk build`. Do not edit.\nreturn new \\Trunk\\Orm\\Compiler\\CompiledOrm(\n    metadata: [\n" . implode("\n", $metaCode) . "\n    ],\n    mappers: [\n" . implode("\n", $mapperCode) . "\n    ],\n);\n";
    }

    private function mapper(EntityMetadata $entity): string
    {
        $class = CodeNames::className($entity->class);
        $arguments = [];
        $optional = [];
        $row = [];

        foreach ($entity->columns as $column) {
            $property = CodeNames::property($column->property);
            if ($column->hidden) {
                $optional[] = '...(\array_key_exists(' . self::literal($column->column) . ', $r) ? [' . self::literal($property) . ' => ' . $this->hydrateExpression($entity, $column) . '] : [])';
            } else {
                $arguments[] = $property . ': ' . $this->hydrateExpression($entity, $column);
            }

            $row[] = self::literal($column->column) . ' => ' . $this->extractExpression($column);
        }

        $id = CodeNames::property($entity->idProperty);

        return "new \\Trunk\\Orm\\Compiler\\CompiledMapper(\n            class: " . self::literal($entity->class) . ",\n            hydrate: static fn(array \$r): {$class} => new {$class}(\n                " . implode(",\n                ", [...$optional, ...$arguments]) . ",\n            ),\n            extract: static fn({$class} \$e): array => [\n                " . implode(",\n                ", $row) . ",\n            ],\n            assign: static fn({$class} \$e, int|string \$id) => (function () use (\$id): void {\n                \$this->{$id} = \$id;\n            })->call(\$e),\n        )";
    }

    private function hydrateExpression(EntityMetadata $entity, ColumnMetadata $column): string
    {
        $c = self::CONVERT;
        $key = '$r[' . self::literal($column->column) . '] ?? null';
        $names = self::literal($entity->class) . ', ' . self::literal($column->column);
        $fast = match ($column->type) {
            Type::Int => 'is_int',
            Type::String => 'is_string',
            Type::Float => 'is_float',
            Type::Bool => 'is_bool',
            default => null,
        };
        $convert = match ($column->type) {
            Type::Int => "{$c}::int(\$v, {$names})",
            Type::String => "{$c}::string(\$v, {$names})",
            Type::Float => "{$c}::float(\$v, {$names})",
            Type::Bool => "{$c}::bool(\$v, {$names})",
            Type::DateTime => "{$c}::dateTime(\$v, {$names})",
            Type::Json => "{$c}::json(\$v, {$names})",
            Type::Enum => "{$c}::enum(\$v, " . self::literal(self::enumClass($column)) . ", {$names})",
        };
        if ($column->nullable) {
            $value = $fast === null ? $convert : "\\{$fast}(\$v) ? \$v : {$convert}";

            return "((\$v = {$key}) === null ? null : ({$value}))";
        }

        if ($fast === null) {
            return str_replace('$v', '(' . $key . ')', $convert);
        }

        return "(\\{$fast}(\$v = {$key}) ? \$v : {$convert})";
    }

    private function extractExpression(ColumnMetadata $column): string
    {
        $property = '$e->' . CodeNames::property($column->property);
        $c = self::CONVERT;

        return match ($column->type) {
            Type::DateTime => "{$c}::dateTimeToDb({$property})",
            Type::Json => "{$c}::jsonToDb({$property})",
            Type::Enum => $column->nullable ? "{$property}?->value" : "{$property}->value",
            default => $property,
        };
    }

    private function metadata(EntityMetadata $entity): string
    {
        $columns = [];

        foreach ($entity->columns as $property => $column) {
            $columns[] = self::literal($property) . ' => new \\Trunk\\Orm\\Mapping\\ColumnMetadata(' . implode(', ', [
                self::literal($column->property),
                self::literal($column->column),
                '\\Trunk\\Orm\\Mapping\\Type::' . $column->type->name,
                var_export($column->nullable, true),
                var_export($column->hidden, true),
                var_export($column->filterable, true),
                var_export($column->sortable, true),
                $column->enum === null ? 'null' : self::literal(self::enumClass($column)),
            ]) . ')';
        }

        $relations = array_map(static fn(RelationMetadata $r): string => self::literal($r->name) . ' => new \\Trunk\\Orm\\Mapping\\RelationMetadata(' . implode(', ', [
            self::literal($r->name),
            '\\Trunk\\Orm\\Mapping\\RelationKind::' . $r->kind->name,
            self::literal($r->target),
            self::literal($r->localColumn),
            self::literal($r->foreignColumn),
            $r->pivotTable === null ? 'null' : self::literal($r->pivotTable),
            $r->pivotLocalColumn === null ? 'null' : self::literal($r->pivotLocalColumn),
            $r->pivotForeignColumn === null ? 'null' : self::literal($r->pivotForeignColumn),
        ]) . ')', $entity->relations);

        return 'new \\Trunk\\Orm\\Mapping\\EntityMetadata(' . implode(', ', [
            self::literal($entity->class),
            self::literal($entity->table),
            self::literal($entity->idProperty),
            var_export($entity->generatedId, true),
            '[' . implode(', ', $columns) . ']',
            '[' . implode(', ', $relations) . ']',
            $entity->softDeleteProperty === null ? 'null' : self::literal($entity->softDeleteProperty),
            $entity->versionProperty === null ? 'null' : self::literal($entity->versionProperty),
            '[' . implode(', ', array_map(self::literal(...), $entity->scopes)) . ']',
            '[' . implode(', ', array_map(self::literal(...), $entity->selectColumns)) . ']',
        ]) . ')';
    }

    private static function literal(string $value): string
    {
        return var_export($value, true);
    }

    /**
     * @return class-string<BackedEnum>
     */
    private static function enumClass(ColumnMetadata $column): string
    {
        $enum = $column->enum;

        if ($enum === null || !ClassName::isValid($enum) || !enum_exists($enum) || !is_subclass_of($enum, BackedEnum::class)) {
            throw new MappingException([\sprintf('"%s" is not a backed enum.', $column->property)]);
        }

        return $enum;
    }
}
