<?php

declare(strict_types=1);

namespace Trunk\Queue\Compiler;

use Trunk\Queue\Job\Field;
use Trunk\Queue\Job\JobMetadata;
use Trunk\Queue\Job\PayloadType;
use Trunk\Support\CodeNames;

/**
 * Emits build/queue.php. Every name written into a code position goes through CodeNames, and
 * every string value through var_export(), so no job or field name can inject code.
 */
final class JobCodeGenerator
{
    private const string CONVERT = '\Trunk\Queue\Job\PayloadConvert';

    /**
     * @param array<string, JobMetadata> $jobs
     */
    public function generate(array $jobs): string
    {
        $entries = [];

        foreach ($jobs as $name => $metadata) {
            $entries[] = '        ' . self::literal($name) . ' => ' . $this->definition($metadata) . ',';
        }

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by `trunk build`. Do not edit.\nreturn new \\Trunk\\Queue\\Compiler\\CompiledJobs([\n" . implode("\n", $entries) . "\n]);\n";
    }

    private function definition(JobMetadata $job): string
    {
        $class = CodeNames::className($job->class);
        $name = self::literal($job->name);
        $c = self::CONVERT;
        $fields = [];
        $encode = [];
        $known = [];
        $decode = [];

        foreach ($job->fields as $field) {
            $property = CodeNames::property($field->name);
            $key = self::literal($property);
            $fields[] = '                new \\Trunk\\Queue\\Job\\Field(' . implode(', ', [$key, '\\Trunk\\Queue\\Job\\PayloadType::' . $field->type->name, var_export($field->nullable, true), var_export($field->optional, true), $field->enum === null ? 'null' : self::literal(ltrim(CodeNames::className($field->enum), '\\'))]) . ')';
            $encode[] = $key . ' => ' . $this->encodeExpression($job, $field, '$j->' . $property);
            $known[] = $key . ' => true';
            $missing = $field->optional ? '' : " else {\n                throw {$c}::missing({$name}, {$key});\n            }";
            $decode[] = "            if (\\array_key_exists({$key}, \$d)) {\n                \$a[{$key}] = " . $this->decodeExpression($job, $field) . ";\n            }" . $missing;
        }

        $dependencies = array_map(static fn(string $d): string => self::literal(ltrim(CodeNames::className($d), '\\')), $job->dependencies);
        $arguments = array_map(static fn(string $d): string => '$c->get(' . $d . ')', $dependencies);
        $options = $job->options;
        $optionsCode = 'new \\Trunk\\Queue\\Job\\JobOptions(' . implode(', ', [var_export($options->tries, true), '[' . implode(', ', array_map(static fn(int $b): string => var_export($b, true), $options->backoff)) . ']', var_export($options->timeout, true), self::literal($options->queue)]) . ')';

        return "new \\Trunk\\Queue\\Compiler\\CompiledDefinition(\n            metadata: new \\Trunk\\Queue\\Job\\JobMetadata(" . self::literal($job->class) . ", {$name}, {$optionsCode}, [\n" . implode(",\n", $fields) . (\count($fields) > 0 ? ',' : '') . "\n            ], [" . implode(', ', $dependencies) . "]),\n            encode: static fn({$class} \$j): array => [" . implode(', ', $encode) . "],\n            decode: static function (array \$d): {$class} {\n                if (\\array_diff_key(\$d, [" . implode(', ', $known) . "]) !== []) {\n                    throw {$c}::unexpected({$name});\n                }\n\n                \$a = [];\n" . implode("\n", $decode) . "\n\n                return new {$class}(...\$a);\n            },\n            invoke: static function (\\Psr\\Container\\ContainerInterface \$c, {$class} \$j): void {\n                \$j->handle(" . implode(', ', $arguments) . ");\n            },\n        )";
    }

    private function encodeExpression(JobMetadata $job, Field $field, string $property): string
    {
        $c = self::CONVERT;
        $expression = match ($field->type) {
            PayloadType::Enum => $field->nullable ? "{$property}?->value" : "{$property}->value",
            PayloadType::DateTime => $field->nullable ? "({$property} === null ? null : {$c}::dateTimeToPayload({$property}))" : "{$c}::dateTimeToPayload({$property})",
            PayloadType::Array => $field->nullable ? "({$property} === null ? null : {$c}::arrayToPayload({$property}, " . self::literal($job->name) . ', ' . self::literal($field->name) . '))' : "{$c}::arrayToPayload({$property}, " . self::literal($job->name) . ', ' . self::literal($field->name) . ')',
            default => $property,
        };

        return $expression;
    }

    private function decodeExpression(JobMetadata $job, Field $field): string
    {
        $c = self::CONVERT;
        $names = self::literal($job->name) . ', ' . self::literal($field->name);
        $value = '$d[' . self::literal($field->name) . ']';
        $convert = fn(string $v): string => match ($field->type) {
            PayloadType::Int => "{$c}::int({$v}, {$names})",
            PayloadType::Float => "{$c}::float({$v}, {$names})",
            PayloadType::String => "{$c}::string({$v}, {$names})",
            PayloadType::Bool => "{$c}::bool({$v}, {$names})",
            PayloadType::Array => "{$c}::array({$v}, {$names})",
            PayloadType::DateTime => "{$c}::dateTime({$v}, {$names})",
            PayloadType::Enum => "{$c}::enum({$v}, " . self::literal(ltrim(CodeNames::className($field->enum ?? ''), '\\')) . ", {$names})",
        };

        return $field->nullable ? "({$value} === null ? null : " . $convert($value) . ')' : $convert($value);
    }

    private static function literal(string $value): string
    {
        return var_export($value, true);
    }
}
