<?php

declare(strict_types=1);

namespace Trunk\Validation\Plan;

use Trunk\Validation\Source;

/**
 * What one request class is made of. Built by reflection in development, generated by `trunk build`
 * for production; the engine runs both the same way.
 */
final readonly class Plan
{
    /**
     * @param class-string    $class
     * @param list<FieldPlan> $fields
     */
    public function __construct(public string $class, public ?Source $source, public array $fields) {}
}
