<?php

declare(strict_types=1);

namespace Trunk\Validation\Compiler;

use Trunk\Support\CodeNames;
use Trunk\Validation\Plan\Plan;

/**
 * Emits `build/validation.php`: one `new Plan(...)` per request class, with its rules written as `new`
 * expressions. Nothing is reflected, parsed or unserialized when the file is loaded.
 */
final class CodeGenerator
{
    /**
     * @param array<class-string, Plan> $plans
     */
    public function generate(array $plans): string
    {
        $entries = [];

        foreach ($plans as $class => $plan) {
            $entries[] = '    ' . Exporter::export(ltrim(CodeNames::className($class), '\\')) . ' => ' . Exporter::export($plan) . ',';
        }

        return "<?php\n\ndeclare(strict_types=1);\n\n// Generated by `trunk build`. Do not edit.\nreturn new \\Trunk\\Validation\\Compiler\\CompiledValidation([\n" . implode("\n", $entries) . "\n]);\n";
    }
}
