<?php

declare(strict_types=1);

namespace Trunk\Router\Compiler;

use Trunk\Foundation\Manifest\ModuleManifest;
use Trunk\Router\Definition\RouteProvider;
use Trunk\Router\Exception\RouteCompilationException;
use Trunk\Support\FileWriter;

/**
 * Build-time only. Collects routes from every manifest module implementing RouteProvider and
 * writes `routes.php`, a file that returns a ready-made RouteTable.
 */
final readonly class RouteArtifactWriter
{
    public function __construct(
        private RouteCompiler $compiler = new RouteCompiler(),
        private FileWriter $files = new FileWriter(),
    ) {}

    /**
     * Collects and compiles routes without touching the filesystem.
     *
     * @throws RouteCompilationException
     */
    public function compile(ModuleManifest $manifest): RouteTable
    {
        $providers = [];

        foreach ($manifest->modules as $class) {
            $module = new $class();

            if ($module instanceof RouteProvider) {
                $providers[] = $module;
            }
        }

        return $this->compiler->compileProviders($providers);
    }

    /**
     * @throws RouteCompilationException
     */
    public function write(ModuleManifest $manifest, string $directory): void
    {
        $this->writeTable($this->compile($manifest), $directory);
    }

    /**
     * @throws RouteCompilationException
     */
    public function writeTable(RouteTable $table, string $directory): void
    {
        if (!is_dir($directory) && !mkdir($directory, 0o755, true) && !is_dir($directory)) {
            throw new RouteCompilationException([\sprintf('Unable to create build directory "%s".', $directory)]);
        }

        $this->files->write($directory . '/routes.php', $this->render($table));
    }

    public function render(RouteTable $table): string
    {
        return "<?php\n\ndeclare(strict_types=1);\n\n"
            . "// Generated by the Trunk compiler. Do not edit.\n\n"
            . 'return new \\' . RouteTable::class . "(\n"
            . '    static: ' . var_export($table->static, true) . ",\n"
            . '    dynamic: ' . var_export($table->dynamic, true) . ",\n"
            . '    routes: ' . var_export($table->routes, true) . ",\n"
            . '    names: ' . var_export($table->names, true) . ",\n"
            . ");\n";
    }
}
